### PR TITLE
Migrated to the latest flask version, 

### LINKED ISSUE #124: Incompatible with current flask-login
Dudel is only compatible to flask-login <= 0.2.11 because the current_user.is_authenticated now is a property instant of a function as used by dudel

### PR DESCRIPTION
**Pull request by h8h**
Fixed #124 Incompatible with current flask.

There a no unit tests., thus it works for me by clicking around the web ui. 

My current setup

```
[h8h@devel dudel]$ uname -a
Linux devel 4.8.10-1-ARCH #1 SMP PREEMPT Mon Nov 21 11:55:43 CET 2016 x86_64 GNU/Linux
```

```
[h8h@devel dudel]$ pip2 list
alembic (0.8.7)
appdirs (1.4.0)
Babel (2.3.4)
blinker (1.4)
click (6.6)
contextlib2 (0.5.4)
enum34 (1.1.6)
Flask (0.11.1)
Flask-Assets (0.12)
Flask-Babel (0.11.1)
Flask-Gravatar (0.4.2)
Flask-Login (0.3.2)
Flask-Mail (0.9.1)
Flask-Markdown (0.3)
Flask-Migrate (2.0.0)
Flask-Script (2.0.5)
Flask-SQLAlchemy (2.1)
Flask-WTF (0.12)
itsdangerous (0.24)
Jinja2 (2.8)
Mako (1.0.4)
Markdown (2.6.6)
MarkupSafe (0.23)
offlineimap (7.0.12)
packaging (16.8)
pip (8.1.2)
psycopg2 (2.6.2)
pyjade (4.0.0)
pyparsing (2.1.10)
python-dateutil (2.5.3)
python-editor (1.0.1)
python-ldap (2.4.27)
pytz (2016.6.1)
raven (5.26.0)
scrypt (0.7.1)
setuptools (30.4.0)
six (1.10.0)
SQLAlchemy (1.0.15)
webassets (0.12.0)
Werkzeug (0.11.11)
WTForms (2.1)
```

The warning are reduced to two warnings:

```
python2 manage.py runserver
/usr/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
/usr/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
 * Debugger is active!
```

Hope this patch works for you. I really love dudel and I appreciate your work so far.

### CODE REVIEW

**Comment by Akasch** [comment]
I will test it in the next days. Thank you for the work.

**Comment by h8h** [comment]
I figured out that `is_anonymous` always returns `true`. Thats very odd because if you're logged in you can't access your Settings and your always vote anonymous.

Since the flask-login has change its `is_anonymous` to a bool insted of a function the User Model class has also be changed to a bool or to a property. 

The same for `is_authenticated` and `is_active`

See [Flask docs](https://flask-login.readthedocs.io/en/latest/#login-example)

**Comment by Akasch** [comment]
make seed breaks as you have removed the constructor from the user model , aside from that it seems good

**Comment by h8h** [comment]
Hi @Akasch 

Sorry for the long delay.

During my tests I've found out that the registration process fails because the registration uses an empty constructor which does not exists. See [views.py](https://github.com/opatut/dudel/blob/master/dudel/views.py#L124). If I revert my changes `make seed` will work, but not the registration. I renamed the constructor to `created` and changed the `make seed`. Now both the registration process and the `make seed` will work.

**Comment by Akasch** [comment]
Looks good.

**Pull request merged**
